version: "3.8"
services:
  envoy:
    image: envoyproxy/envoy:v1.21-latest
    ports:
      - "8081:80"
      - "8001:8001"
    volumes:
      - ./envoy.yaml:/config/envoy.yaml
    command: 
      - -c
      - /config/envoy.yaml
      - -l
      - debug

  app:
    build: ./simple-web
    ports:
      - "8080:8080"